# Cloudflare Pages Configuration
name = "codingbull-website"
compatibility_date = "2024-01-01"

[build]
command = "npm run build:prod"
destination = "build"

[env.production]
# Production environment variables for Cloudflare Pages
REACT_APP_ENV = "production"
REACT_APP_API_BASE_URL = "https://codingbull-backend.koyeb.app/api/v1"
REACT_APP_ENABLE_DEBUG_MODE = "false"
REACT_APP_ENABLE_ANALYTICS = "true"
GENERATE_SOURCEMAP = "false"

[env.preview]
# Preview environment variables
REACT_APP_ENV = "development"
REACT_APP_API_BASE_URL = "https://codingbull-backend.koyeb.app/api/v1"
REACT_APP_ENABLE_DEBUG_MODE = "true"
REACT_APP_ENABLE_ANALYTICS = "false"
