# Koyeb Deployment Configuration for CodingBull Backend
apiVersion: koyeb.io/v1
kind: App
metadata:
  name: codingbull-backend
spec:
  services:
    - name: api
      git:
        repository: https://github.com/your-username/codingbull
        branch: main
        workdir: codingbull_backend
      instance:
        type: nano  # Free tier
      ports:
        - port: 8000
          protocol: http
      env:
        - name: DJANGO_SECRET_KEY
          value: "your-production-secret-key-here"
        - name: DJANGO_ENV
          value: "production"
        - name: DJANGO_DEBUG
          value: "False"
        - name: DJANGO_ALLOWED_HOSTS
          value: "codingbull-backend.koyeb.app,codingbullz.com,www.codingbullz.com"
        - name: DATABASE_URL
          value: "postgresql://bulldb:Bull@2747.@localhost:5432/bulldb"
        - name: CORS_ALLOWED_ORIGINS_PRODUCTION
          value: "https://codingbullz.com,https://www.codingbullz.com"
        - name: SECURE_SSL_REDIRECT
          value: "True"
        - name: SESSION_COOKIE_SECURE
          value: "True"
        - name: CSRF_COOKIE_SECURE
          value: "True"
      build:
        command: |
          pip install -r ../requirements.txt
          python manage.py collectstatic --noinput
          python manage.py migrate
      run:
        command: gunicorn codingbull_api.wsgi:application --bind 0.0.0.0:8000 --workers 2
