# Generated by Django 5.2.1 on 2025-05-30 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_testimonial_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='tags',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
