# Generated by Django 5.2.1 on 2025-06-01 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_ipaddress_ratelimitrule_ratelimittracker_securitylog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='project_logos/'),
        ),
    ]
