# Generated by Django 5.2.1 on 2025-06-01 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_testimonial_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinquiry',
            name='phone',
            field=models.CharField(default=9898567412, max_length=20),
            preserve_default=False,
        ),
    ]
