# Generated by Django 5.2.1 on 2025-06-02 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_contactinquiry_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='faqs',
            field=models.JSONField(blank=True, default=list, help_text='Frequently asked questions'),
        ),
        migrations.AddField(
            model_name='service',
            name='features',
            field=models.JSONField(blank=True, default=list, help_text='List of service features with icon, title, description'),
        ),
        migrations.AddField(
            model_name='service',
            name='icon_emoji',
            field=models.CharField(blank=True, help_text='Emoji icon for the service', max_length=10),
        ),
        migrations.AddField(
            model_name='service',
            name='image_url',
            field=models.URLField(blank=True, help_text='Hero image URL for service page'),
        ),
        migrations.AddField(
            model_name='service',
            name='long_description',
            field=models.TextField(blank=True, help_text='Detailed description for service page'),
        ),
        migrations.AddField(
            model_name='service',
            name='process_steps',
            field=models.JSONField(blank=True, default=list, help_text='Process steps for the service'),
        ),
        migrations.AddField(
            model_name='service',
            name='related_services',
            field=models.JSONField(blank=True, default=list, help_text='Related services slugs'),
        ),
        migrations.AddField(
            model_name='service',
            name='technologies',
            field=models.JSONField(blank=True, default=list, help_text='Technologies used for this service'),
        ),
    ]
